# Generated by Django 6.0 on 2025-12-30 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeCategory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HouseFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(choices=[('D', 'Detached'), ('S', 'Semi-Detached'), ('T', 'Terraced'), ('F', 'Flats/Maisonettes'), ('O', 'Other')], max_length=1)),
                ('tenure_code', models.CharField(choices=[('F', 'Freehold'), ('L', 'Leasehold')], max_length=1)),
                ('is_new_build', models.BooleanField(default=False)),
                ('transaction_category', models.CharField(choices=[('A', 'Standard Price Paid Entry'), ('B', 'Additional Price Paid Entry for New Build Properties')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Name must be a valid UK Postcode Sector (e.g. 'RG1 1').", regex='^[A-Z]{1,2}[0-9][A-Z0-9]? [0-9]$')])),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('population', models.IntegerField(default=0)),
                ('nearby_sectors', models.ManyToManyField(blank=True, to='api.coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='HouseAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary Address')),
                ('paon', models.CharField(max_length=255, verbose_name='Primary Address')),
                ('street', models.CharField(max_length=255)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(max_length=20)),
                ('postcode_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='api.coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='HouseSaleRecord',
            fields=[
                ('unique_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price_paid', models.DecimalField(decimal_places=0, max_digits=12)),
                ('deed_date', models.DateField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.houseaddress')),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.housefeatures')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('urn', models.CharField(max_length=20, unique=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('address3', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(max_length=20)),
                ('school_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_secondary', models.BooleanField(default=False)),
                ('is_post16', models.BooleanField(default=False)),
                ('minimum_age', models.IntegerField(blank=True, null=True)),
                ('maximum_age', models.IntegerField(blank=True, null=True)),
                ('postcode_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='api.coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='KS5Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(help_text='The academic year of publication (Format: YYYY)', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)])),
                ('a_level_points', models.DecimalField(decimal_places=2, help_text='Average points per entry', max_digits=5, null=True)),
                ('a_level_grade', models.CharField(blank=True, help_text='Average grade (e.g. B-)', max_length=5, null=True)),
                ('academic_points', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('academic_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ks5_results', to='api.school')),
            ],
            options={
                'unique_together': {('school', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='KS4Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(help_text='The academic year of publication (Format: YYYY)', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)])),
                ('progress_8', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('attainment_8', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ks4_results', to='api.school')),
            ],
            options={
                'unique_together': {('school', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='KS2Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(help_text='The academic year of publication (Format: YYYY)', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)])),
                ('pct_meeting_expected', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('reading_score', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('maths_score', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ks2_results', to='api.school')),
            ],
            options={
                'unique_together': {('school', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SectorCrimeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crimecategory')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime_stats', to='api.coordinates')),
            ],
            options={
                'unique_together': {('sector', 'category')},
            },
        ),
    ]
