# Generated by Django 6.0 on 2025-12-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('population', models.IntegerField(default=0)),
                ('nearby_sectors', models.ManyToManyField(blank=True, to='api.coordinates')),
            ],
        ),
    ]
