# Generated by Django 6.0 on 2025-12-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='households',
            field=models.IntegerField(default=0),
        ),
    ]
