# Generated by Django 6.0 on 2025-12-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='population',
        ),
    ]
