# Generated by Django 6.0 on 2025-12-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coordinates_households'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='total_crimes',
            field=models.IntegerField(default=0),
        ),
    ]
