# Generated by Django 6.0 on 2025-12-23 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_coordinates_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Name must be a valid UK Postcode Sector (e.g. 'RG1 1').", regex='^[A-Z]{1,2}[0-9][A-Z0-9]? [0-9]$')]),
        ),
    ]
