# Generated by Django 6.0 on 2025-12-31 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coordinates_total_crimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransportStop',
            fields=[
                ('stop_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('nearest_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_stops', to='api.coordinates')),
                ('routes', models.ManyToManyField(blank=True, related_name='stops', to='api.busroute')),
            ],
        ),
    ]
