# Generated by Django 6.0 on 2025-12-24 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coordinates_population_alter_coordinates_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeCategory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SectorCrimeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crimecategory')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime_stats', to='api.coordinates')),
            ],
            options={
                'unique_together': {('sector', 'category')},
            },
        ),
    ]
