# Generated by Django 6.0 on 2025-12-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_crimecategory_sectorcrimestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paon', models.CharField(max_length=255, verbose_name='Primary Address')),
                ('saon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary Address')),
                ('street', models.CharField(max_length=255)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(max_length=20)),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.coordinates')),
            ],
            options={
                'unique_together': {('paon', 'saon', 'postcode')},
            },
        ),
        migrations.CreateModel(
            name='HouseFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(choices=[('D', 'Detached'), ('S', 'Semi-Detached'), ('T', 'Terraced'), ('F', 'Flats/Maisonettes'), ('O', 'Other')], max_length=1)),
                ('tenure_code', models.CharField(choices=[('F', 'Freehold'), ('L', 'Leasehold')], max_length=1)),
                ('is_new_build', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('type_code', 'tenure_code', 'is_new_build')},
            },
        ),
        migrations.CreateModel(
            name='HouseSale',
            fields=[
                ('unique_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deed_date', models.DateField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.address')),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.housefeatures')),
            ],
        ),
    ]
