# Generated by Django 6.0 on 2025-12-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_address_housefeatures_housesale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='coordinate',
            new_name='postcode_sector',
        ),
    ]
