# Generated by Django 6.0 on 2025-12-25 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_coordinate_address_postcode_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('address3', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(max_length=20)),
                ('school_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('postcode_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='api.coordinates')),
            ],
        ),
    ]
