# Generated by Django 6.0 on 2025-12-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_post16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='is_secondary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='maximum_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='minimum_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
