# Generated by Django 6.0 on 2025-12-25 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_school_is_post16_school_is_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KS2Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(default=2024)),
                ('pct_meeting_expected', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('reading_score', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('maths_score', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ks2_results', to='api.school')),
            ],
            options={
                'unique_together': {('school', 'academic_year')},
            },
        ),
    ]
