# Generated by Django 6.0 on 2025-12-25 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ks2performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ks2performance',
            name='academic_year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='KS4Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('progress_8', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('attainment_8', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ks4_results', to='api.school')),
            ],
            options={
                'unique_together': {('school', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='KS5Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(default=2023)),
                ('a_level_points', models.DecimalField(decimal_places=2, help_text='Average points per entry', max_digits=5, null=True)),
                ('a_level_grade', models.CharField(blank=True, help_text='Average grade (e.g. B-)', max_length=5, null=True)),
                ('academic_points', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('academic_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ks5_results', to='api.school')),
            ],
            options={
                'unique_together': {('school', 'academic_year')},
            },
        ),
    ]
