# Generated by Django 6.0 on 2025-12-25 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_ks2performance_academic_year_ks4performance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='urn',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ks2performance',
            name='academic_year',
            field=models.IntegerField(help_text='The academic year of publication (Format: YYYY)', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)]),
        ),
        migrations.AlterField(
            model_name='ks4performance',
            name='academic_year',
            field=models.IntegerField(help_text='The academic year of publication (Format: YYYY)', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)]),
        ),
        migrations.AlterField(
            model_name='ks5performance',
            name='academic_year',
            field=models.IntegerField(help_text='The academic year of publication (Format: YYYY)', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)]),
        ),
    ]
