# Generated by Django 6.0 on 2025-12-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_school_urn_alter_ks2performance_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='urn',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
