# Generated by Django 6.0 on 2025-12-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_school_urn'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='housefeatures',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='housefeatures',
            name='transaction_category',
            field=models.CharField(choices=[('A', 'Standard Price Paid Entry'), ('B', 'Additional Price Paid Entry for New Build Properties')], default='A', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='housefeatures',
            unique_together={('type_code', 'tenure_code', 'is_new_build', 'transaction_category')},
        ),
    ]
