# Generated by Django 6.0 on 2025-12-30 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_housefeatures_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseSale',
            new_name='HouseSaleRecord',
        ),
    ]
