# Generated by Django 6.0 on 2025-12-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_housesale_housesalerecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='HouseAddress',
        ),
    ]
